# Generated by Django 4.0.2 on 2022-02-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Food', 'Food'), ('Gifts', 'Gifts'), ('Groceries', 'Groceries'), ('Miscellaneous', 'Miscellaneous'), ('Recreations', 'Recreations'), ('Rent', 'Rent'), ('Subscriptions', 'Subscriptions'), ('Transportation', 'Transportation'), ('Water', 'Water')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exp_v1.user')),
            ],
        ),
    ]
