# Generated by Django 4.0.2 on 2022-02-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='username',
        ),
    ]
