# Generated by Django 4.0.2 on 2022-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_v1', '0004_expense_amount_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
